version: '3.1'

services:
  nginx:
    image: nginx:1.18-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
      - db
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app.create_app:create_app()"
    volumes:
      - ./:/var/www
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    networks:
      my-network:
        aliases:
          - flask-app
  db:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network: